import {Model} from './model'
export class Summary extends Model {
    PIN: number
    FiscalYear: number
    OperatingDays: number
    CertifiedBedCount: number
    SpecialServiceRevenue: number
    ComprehensivePayor1Name: string
    ComprehensivePayor2Name: string
    ComprehensivePayor3Name: string
    PrivateDays: number
    MedicareDays: number
    MedicaidDays: number
    ComprehensivePayor1Days: number
    ComprehensivePayor2Days: number
    ComprehensivePayor3Days: number
    OtherComprehensiveDays: number
    ComprehensiveDays: number
    OtherCareDays: number
    TotalDays: number
    PrivateRevenue: number
    UnadjustedMedicareRevenue: number
    MedicaidRevenue: number
    ComprehensiveCareCustom1InsuranceDays: number
    ComprehensiveCareCustom2InsuranceDays: number
    ComprehensiveCareCustom3InsuranceDays: number
    UnadjustedComprehensivePayor1Revenue: number
    UnadjustedComprehensivePayor2Revenue: number
    UnadjustedComprehensivePayor3Revenue: number
    UnadjustedOtherComprehensiveRevenue: number
    ComprehensiveRevenue: number
    OtherRevenue: number
    GovernmentAndAdministrativeExpense: number
    DietaryExpense: number
    HousekeepingAndLaundryExpense: number
    NursingCareExpense: number
    OtherPatientCareExpense: number
    PropertyExpense: number
    RealEstateTax: number
    MedicareRevenue: number
    ComprehensivePayor1Revenue: number
    ComprehensivePayor2Revenue: number
    ComprehensivePayor3Revenue: number
    OtherComprehensiveRevenue: number
    PrivateDaysPercent: number
    MedicareDaysPercent: number
    MedicaidDaysPercent: number
    OtherComprehensiveDaysPercent: number
    PrivateDailyCensus: number
    MedicareDailyCensus: number
    MedicaidDailyCensus: number
    ComprehensivePayor1DailyCensus: number
    ComprehensivePayor2DailyCensus: number
    ComprehensivePayor3DailyCensus: number
    ComprehensivePayor1DailyCensusPercent: number
    ComprehensivePayor2DailyCensusPercent: number
    ComprehensivePayor3DailyCensusPercent: number
    OtherComprehensiveDailyCensus: number
    ComprehensiveDailyCensus: number
    AvailableDays: number
    PrivateRevenuePerDay: number
    MedicareRevenuePerDay: number
    MedicaidRevenuePerDay: number
    ComprehensivePayor1RevenuePerDay: number
    ComprehensivePayor2RevenuePerDay: number
    ComprehensivePayor3RevenuePerDay: number
    OtherComprehensiveRevenuePerDay: number
    ComprehensiveRevenuePerDay: number
    OtherRevenuePerDay: number
    TotalRevenue: number
    GovernmentAndAdministrativeExpensePerDay: number
    DietaryExpensePerDay: number
    HousekeepingAndLaundryExpensePerDay: number
    NursingCareExpensePerDay: number
    OtherPatientCareExpensePerDay: number
    PropertyExpensePerDay: number
    RealEstateTaxPerDay: number
    TotalExpense: number
    TotalRevenuePerDay: number
    ComprehensiveRevenuePercent: number
    OtherRevenuePercent: number
    TotalExpensePerDay: number
    TotalExpensePerRevenuePercent: number
    GovernmentAndAdministrativeExpensePerRevenuePercent: number
    DietaryExpensePerRevenuePercent: number
    HousekeepingAndLaundryExpensePerRevenuePercent: number
    NursingCareExpensePerRevenuePercent: number
    OtherPatientCareExpensePerRevenuePercent: number
    PropertyExpensePerRevenuePercent: number
    RealEstateTaxPerRevenuePercent: number
    NetIncome: number
    NetIncomePerDay: number
    NetIncomePerRevenuePercent: number
    NetIncomePerBed: number
    ImpliedMinValue: number
    ImpliedMinValuePerBed: number
    ImpliedMaxValue: number
    ImpliedMaxValuePerBed: number
    NursingOccupancyPercent: number
}